Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using DizonCoop.Entities;
using DizonCoop.Models;
using Microsoft.AspNetCore.Mvc;


namespace DizonCoop.Controllers
{
    public class ClientController : Controller
    {
        private readonly DizonCoopContext _context;

        public ClientController(DizonCoopContext context)
        {
            _context = context;

        }

        public async Task<IActionResult> Index()
        {
            var clientInfos = (
            from clientInfo in _context.ClientInfos
            join usertype in _context.UserTypes
            on clientInfo.Usertype equals usertype.Id
            select new ClientInfoViewModel
            {
                Id = clientInfo.Id,
                Usertype = clientInfo.Usertype,
                UsertypeName = usertype.Name,
                FirstName = clientInfo.FirstName,
                MiddleName = clientInfo.MiddleName,
                LastName = clientInfo.LastName,
                Address = clientInfo.Address,
                ZipCode = clientInfo.ZipCode,
                BirthDate = clientInfo.BirthDate,
                Age = clientInfo.Age,
                NameOfFather = clientInfo.NameOfFather,
                NameOfMother = clientInfo.NameOfMother,
                CivilStatus = clientInfo.CivilStatus,
                Relgion = clientInfo.Relgion,
                Occupation = clientInfo.Occupation,
            }
        ).ToList();

            return View(clientInfos);
            // ViewData["types"] =  _context.UserTypes.ToList();
            // ViewData["clientinfo"] = _context.ClientInfos.ToList();
            // return View();
        }

        [HttpPost]
        public ActionResult Create(ClientInfoViewModel clientinfo)
        {

            if (!ModelState.IsValid)
                return View(clientinfo);

            ClientInfo c = new ClientInfo
            {
                Id = clientinfo.Id,
                Usertype = clientinfo.Usertype,
                FirstName = clientinfo.FirstName,
                MiddleName = clientinfo.MiddleName,
                LastName = clientinfo.LastName,
                Address = clientinfo.Address,
                ZipCode = clientinfo.ZipCode,
                BirthDate = clientinfo.BirthDate,
                Age = clientinfo.Age,
                NameOfFather = clientinfo.NameOfFather,
                NameOfMother = clientinfo.NameOfMother,
                CivilStatus = clientinfo.CivilStatus,
                Relgion = clientinfo.Relgion,
                Occupation = clientinfo.Occupation
            };

            _context.ClientInfos.Add(c);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(ClientInfoViewModel clientinfo)
        {

            if (!ModelState.IsValid)
                return View(clientinfo);

            ClientInfo s = new ClientInfo
            {
                Id = clientinfo.Id,
                Usertype = clientinfo.Usertype,
                FirstName = clientinfo.FirstName,
                MiddleName = clientinfo.MiddleName,
                LastName = clientinfo.LastName,
                Address = clientinfo.Address,
                ZipCode = clientinfo.ZipCode,
                BirthDate = clientinfo.BirthDate,
                Age = clientinfo.Age,
                NameOfFather = clientinfo.NameOfFather,
                NameOfMother = clientinfo.NameOfMother,
                CivilStatus = clientinfo.CivilStatus,
                Relgion = clientinfo.Relgion,
                Occupation = clientinfo.Occupation
            };

            _context.ClientInfos.Update(s);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }





        // [HttpGet]
        // public ActionResult Update(int id)
        // {
        //     var client = _context.ClientInfos
        //                     .Where(q => q.Id == id )
        //                     .Select(s => new ClientInfoViewModel {
        //                         Id = s.Id,
        //                         Usertype = s.Usertype,
        //                         FirstName = s.FirstName,
        //                         MiddleName = s.MiddleName,
        //                         LastName = s.LastName,
        //                         Address = s.Address,
        //                         ZipCode = s.ZipCode,
        //                         BirthDate = s.BirthDate,
        //                         Age = s.Age,
        //                         NameOfFather = s.NameOfFather,
        //                         NameOfMother = s.NameOfMother,
        //                         CivilStatus = s.CivilStatus,
        //                         Relgion = s.Relgion,
        //                         Occupation = s.Occupation
        //                     })
        //                     .FirstOrDefault();
        //     return RedirectToAction("Index");
        // }

        // [HttpPost]
        // public ActionResult Update(ClientInfoViewModel clientinfo) {

        //     if(!ModelState.IsValid)
        //     return View(clientinfo);

        //     ClientInfo c = new ClientInfo
        //     {
        //         Id = clientinfo.Id,
        //         Usertype = clientinfo.Usertype,
        //         FirstName = clientinfo.FirstName,
        //         MiddleName = clientinfo.MiddleName,
        //         LastName = clientinfo.LastName,
        //         Address = clientinfo.Address,
        //         ZipCode = clientinfo.ZipCode,
        //         BirthDate = clientinfo.BirthDate,
        //         Age = clientinfo.Age,
        //         NameOfFather = clientinfo.NameOfFather,
        //         NameOfMother = clientinfo.NameOfMother,
        //         CivilStatus = clientinfo.CivilStatus,
        //         Relgion = clientinfo.Relgion,
        //         Occupation = clientinfo.Occupation
        //     };

        //     _context.ClientInfos.Update(c);
        //     _context.SaveChanges();

        //     return RedirectToAction("Index");
        // }

        // public ActionResult ModalUpdate(){
        //     return PartialView("partial/_ModalUpdate");
        // }

        public ActionResult ModalCreate()
        {
            return PartialView("partial/_ModalCreate");
        }

        public async Task<IActionResult> _ParitalTable(int? id)
        {
            if (id == null || _context.ClientInfos == null)
            {
                return NotFound();
            }

            var clientInfo = await _context.ClientInfos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clientInfo == null)
            {
                return NotFound();
            }

            return View(clientInfo);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var client = _context.ClientInfos.Where(q => q.Id == id).FirstOrDefault();
            _context.ClientInfos.Remove(client);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Controllers/UserTypeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DizonCoop.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.Extensions.Logging;

namespace DizonCoop.Controllers
{
    public class UserTypeController : Controller
    {
        private readonly DizonCoopContext _context;
        public UserTypeController(DizonCoopContext userType)
        {
            _context = userType;
            
        }

        public IActionResult Index()
        {   
            var userType = _context.UserTypes.ToList();
            return View(userType);
        }

        public IActionResult getTable()
        {   

            return PartialView("partialTable");
        }

    

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]

        public IActionResult Create(UserType usertype)
        {
            if(!ModelState.IsValid)
            return View(usertype);

            _context.UserTypes.Add(usertype);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id) {
            var userType = _context.UserTypes.Where( q => q.Id == id).FirstOrDefault();
            return View(userType);
        }

        [HttpPost]
        public IActionResult Update(UserType usertype) {

            if(!ModelState.IsValid)
                return View(usertype);

            _context.UserTypes.Update(usertype);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id) {
            var userType = _context.UserTypes.Where( q => q.Id == id).FirstOrDefault();
            _context.UserTypes.Remove(userType);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DizonCoop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DizonCoop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DizonCoop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserType" asp-action="Index">User Type</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Client Info</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DizonCoop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>